language: node_js
node_js:
  - 12
os: linux
dist: xenial
cache:
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message: 'Deploy del proyecto'
  on:
    branch: master